pipeline:
  name: Build node-harness-demo
  identifier: Build_node_harness_demo_1790525711425
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
              - step:
                  type: Run
                  name: install-and-test
                  identifier: installandtest
                  spec:
                    connectorRef: ghcr
                    image: node:22-alpine
                    shell: Sh
                    command: |-
                      echo "Installing dependencies..."
                      npm install
                      echo "Running tests..."
                      npm test
                  description: install-and-test
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
    - stage:
        name: push-image
        identifier: pushimage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: ghcr
                    repo: ghcr.io/sakshssy/node-harness-demo
                    tags:
                      - latest
  properties:
    ci:
      codebase:
        connectorRef: github_connector
        repoName: node-harness-demo
        build: <+input>
